### ISSUE TITLE
Allow user to specify database user and password

### ISSUE THREAD

**Issue by lmcarril** [swarm64/s64da-benchmark-toolkit#17]
The toolkit always assumes that the user can run it with the postgres user and no password. But is not necessarily the case, as the user may want to run it against a DB with no SSH access (or access to the postgres user), such as in AWS RDS.

For querying this is doable if the user knows the dsn syntax, which is only partially written in the README.
For data loading, the README says that is not possible, although the loader.sh files use also the dsn, so a similar approach would be possible.

**Comment by sdressler** [comment]
Thanks for the input. Actually DSNs are now possible with the Python loaders, so we'll update the README to make that clear. `loader.sh` could be changed as well.

**Comment by lmcarril** [comment]
With the loader scripts gone, this is no longer an issue as the user must specify the whole DSN
