### ISSUE TITLE
use the right settings for 4.1.0

### ISSUE THREAD

**Issue by lucvlaming** [swarm64/s64da-benchmark-toolkit#34]
when using the latest toolkit i get warnings:

`2020-05-19 17:06:29.572 UTC [1383] WARNING:  'optimization_level_target' option is deprecated and no longer has any effect`
`2020-05-19 18:50:53.413 UTC [2167] WARNING:  'primary_key' option is deprecated, replacing by 'primary_key_hint' instead`
`2020-05-19 18:50:53.428 UTC [2169] WARNING:  'foreign_keys' option is deprecated, replacing by 'foreign_keys_hint' instead
`

**Comment by jukoson** [comment]
This should be fixed by now. Cannot reproduce with the v4.1.0 tag that loads tpch 10 data into a 4.1.0 image.
Closing this issue.
